export const docsLinks = [
  {
    href: "/docs",
    label: "Xmatter",
    group: "Documentation",
    keywords: [
      "overview",
      "introduction",
      "getting started",
      "motivation",
      "metadata",
      "registry",
      "smart contracts",
      "frontpage",
      "address",
      "blockchain",
      "token",
      "npm",
      "assets",
      "on-chain",
      "license",
      "mit",
      "busl",
      "readme",
      "yaml",
    ],
  },
  {
    href: "/docs/contributing",
    label: "Contributing",
    group: "Documentation",
    keywords: [
      "contribute",
      "submit",
      "add",
      "new",
      "record",
      "entry",
      "pull request",
      "fork",
      "github",
      "namespace",
      "evm",
      "svm",
      "tvm",
      "eip155",
      "solana",
      "tip474",
      "chain id",
      "directory",
      "readme",
      "icon",
      "png",
      "svg",
      "jpg",
      "jpeg",
      "frontmatter",
      "yaml",
      "agent",
      "lock",
      "automated",
      "ethereum",
      "optimism",
      "bnb",
      "polygon",
      "base",
      "arbitrum",
      "celo",
      "avalanche",
      "lowercase",
      "checksum",
    ],
  },
  {
    href: "/docs/standards/path",
    label: "Resource URI",
    group: "Standards",
    keywords: [
      "uri",
      "caip-10",
      "identifier",
      "address",
      "caip-19",
      "path",
      "url",
      "url-safe",
      "namespace",
      "eip155",
      "solana",
      "tip474",
      "chain",
      "resource",
      "filesystem",
      "structure",
      "canonical",
      "evm",
      "svm",
      "tvm",
      "wrapped ether",
      "weth",
    ],
  },
  {
    href: "/docs/standards/markdown",
    label: "README.md",
    group: "Standards",
    keywords: [
      "frontmatter",
      "yaml",
      "metadata",
      "schema",
      "readme",
      "markdown",
      "name",
      "symbol",
      "decimals",
      "provenance",
      "standards",
      "description",
      "tags",
      "links",
      "icons",
      "color",
      "erc20",
      "weth",
      "interface",
      "type",
      "typescript",
    ],
  },
  {
    href: "/docs/standards/provenance",
    label: "Provenance",
    group: "Standards",
    keywords: [
      "provenance",
      "metadata source",
      "data origin",
      "source url",
      "attribution",
      "audit trail",
      "registry metadata",
      "token metadata",
      "upstream repository",
      "github repository",
      "official source",
      "contributor",
      "maintainer",
      "transparency",
      "verification",
      "authenticity",
      "required field",
      "schema",
      "zod",
      "validation",
      "trust",
      "trust wallet",
      "url",
      "github profile",
      "website",
      "debugging",
      "best practices",
    ],
  },
  {
    href: "/docs/api",
    label: "API Reference",
    group: "Developers",
    keywords: [
      "rest",
      "endpoint",
      "http",
      "fetch",
      "api",
      "index.txt",
      "frontmatter.json",
      "icon",
      "icon.webp",
      "readme.md",
      "prefix",
      "existence",
      "cache",
      "cache-control",
      "json",
      "webp",
      "png",
      "svg",
      "jpg",
      "namespace",
      "chainid",
      "address",
      "weth",
      "eip155",
      "solana",
      "tip474",
      "256x256",
      "optimize",
    ],
  },
  {
    href: "/docs/javascript",
    label: "JavaScript Client",
    group: "Developers",
    keywords: [
      "sdk",
      "npm",
      "typescript",
      "library",
      "client",
      "xmatterclient",
      "javascript",
      "has",
      "getfrontmatter",
      "geticonurl",
      "geticonwebpurl",
      "getindex",
      "prefix",
      "index",
      "cache",
      "lru",
      "404",
      "rate limit",
      "namespace",
      "chainid",
      "address",
      "baseurl",
      "error",
      "xmattererror",
      "async",
      "await",
      "promise",
    ],
  },
  {
    href: "/docs/nextjs",
    label: "Next.js Integration",
    group: "Developers",
    keywords: [
      "react",
      "ssr",
      "framework",
      "vercel",
      "nextjs",
      "next.js",
      "component",
      "xmattericon",
      "server component",
      "client component",
      "remotepattern",
      "next/image",
      "image optimization",
      "async",
      "fallback",
      "namespace",
      "chainid",
      "address",
      "props",
      "imageprops",
      "width",
      "height",
      "alt",
      "404",
      "prefix index",
      "existence check",
    ],
  },
  {
    href: "/docs/rate-limits",
    label: "Rate Limits",
    group: "Developers",
    keywords: [
      "throttle",
      "quota",
      "limit",
      "usage",
      "rate",
      "300",
      "per minute",
      "fair use",
      "abuse",
      "cache",
      "cache-control",
      "cors",
      "preflight",
      "proxy",
      "cdn",
      "404",
      "prefix",
      "index",
      "sponsors",
      "customized",
      "higher volume",
      "contact",
    ],
  },
];

export const docsGroups = Array.from(new Set(docsLinks.map((d) => d.group)));
