name: Agent

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/agent.yml
      - packages/agent-*/**/*
      - "!packages/agent-*/.fetch-ignore.json"
  schedule:
    - cron: "30 14 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - agent: agent-icon-color
          - agent: agent-trust-wallet
            repo: trustwallet/assets
            ref: master
          - agent: agent-ethereum-optimism
            repo: ethereum-optimism/ethereum-optimism.github.io
            ref: master
          - agent: agent-smol-dapp
            repo: SmolDapp/tokenAssets
            ref: main
          - agent: agent-viaprotocol
            repo: viaprotocol/tokenlists
            ref: main
          - agent: agent-polygon
            repo: maticnetwork/polygon-token-list
            ref: dev
          - agent: agent-ethereum-lists
            repo: ethereum-lists/tokens
            ref: master
          - agent: agent-elkfinance
            repo: elkfinance/tokens
            ref: main
          - agent: agent-uniswap
            repo: Uniswap/default-token-list
            ref: main
          - agent: agent-pancakeswap
            repo: pancakeswap/token-list
            ref: main
          - agent: agent-pangolin
            repo: pangolindex/tokenlists
            ref: main
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - uses: actions/checkout@v7
        if: matrix.repo && matrix.ref
        with:
          # PLEASE be aware that this is a security risk when you allow untrusted repositories to be checked out.
          # While the agent is executed such that we're only reading files which pose no security risk,
          # it's nonetheless possible through other means to execute arbitrary code
          # when you attempt to do "TOO MUCH" outside its intended use case.
          path: packages/${{ matrix.agent }}/.repo
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}

      - run: bun run agent
        working-directory: packages/${{ matrix.agent }}

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          title: "chore(agent): ${{ matrix.agent }}"
          body: "${{ matrix.agent }}"
          commit-message: "chore(agent): ${{ matrix.agent }}"
          branch: agents/${{ matrix.agent }}
          draft: always-true
