name: Publish

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish [npm]
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - run: jq --arg v "${GITHUB_REF_NAME#v}" '.version = $v' package.json > package.json.tmp && mv package.json.tmp package.json
        working-directory: packages/xmatter

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - run: bunx turbo run build --filter xmatter

      - run: npm publish --provenance --access public
        working-directory: packages/xmatter
